<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="P_Invoke" Id="{186187b0-d27d-4c73-ad36-5d0ff2124d6a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Invoke
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P_Invoke">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>