<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="P_Invoke" Id="{186187b0-d27d-4c73-ad36-5d0ff2124d6a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Invoke
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Meth" Id="{d6bac87f-ee1a-4924-bdf7-1aac2b686ad8}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD Meth : INT
VAR_INPUT
	Value : INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Meth := Value*2;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>