<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="P_Notifications" Id="{8e195bf0-9a3a-4b45-b03a-44b3843a5af3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Notifications
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P_Notifications">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>