<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="P_Write" Id="{516125b6-7d34-4d90-99da-f27ea541b47a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Write
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P_Write">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>