<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FB_Complex" Id="{e45034a7-979a-4ae9-ad47-43216a229aae}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Complex
VAR
	_fMember 		: LREAL;
	_stMember 		: ST_Complex; 
	_fbSimpleMember : FB_Simple(TRUE, 78, 'Complex Test.');
	_fbPackedMember : FB_Packed;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Complex">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>